### ISSUE TITLE
Usage with default.nix only

### ISSUE THREAD

**Issue by fleimgruber** [mitchellh/zig-overlay#39]
As a potential user, I read "the default.nix can also be imported directly by non-flakes, too."

I tried to use the `.envrc` and the `default.nix` with `direnv allow`, which gave "error: opening file '/.../sources.json': No such file or directory". After downloading the `sources.json` and re-running, I get:

```
direnv: loading ~/.../.envrc
direnv: using nix
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```

but I expected to get the [latest released version](https://github.com/mitchellh/zig-overlay/blob/main/default.nix#L63).

**Comment by mitchellh** [comment]
I haven't used non-flake Nix in years so I'm not sure how its supposed to work exactly, but `default.nix` exposes all the same `packages` sub-attributes that the Flake does, so you can access all of the same packages. It isn't -- on its own -- a single derivation. You'd have to do something like this:

```
(import /path/to/overlay/default.nix).master
```

Or something. If you have a suggestion to improve the README in some way, I'm happy to incorporate it. I'm not sure what changes to make myself since like I said, I haven't used a non-flake enabled Nix in a 2 or 3 years now.

**Comment by fleimgruber** [comment]
Thanks for the super quick reply and information! I will need to look into this more on my end then or finally bite the flake.
